import { useEffect, useRef, useState } from 'react';
import { onAuthStateChanged, signInWithPopup, signOut } from 'firebase/auth';
import { addDoc, collection, limit, onSnapshot, orderBy, query, serverTimestamp, where } from 'firebase/firestore';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { Activity, ArrowDownToLine, ArrowRight, ChartCandlestick, Check, ChevronDown, CircleHelp, Clock3, Command, Expand, FileText, History, Layers3, LoaderCircle, LogOut, Radio, ShieldCheck, Sparkles, X } from 'lucide-react';
import { auth, db, provider } from './firebase';
import { DRAWINGS, MAX_INSTRUCTION, MODES, PRESETS, TIMEFRAMES, validateRequest } from '../../shared/validation';

const STATUS = { pending: 'Menunggu', processing: 'Diproses', completed: 'Selesai', failed: 'Gagal' };
const DEMO = new URLSearchParams(location.search).get('demo') === '1' && ['localhost', '127.0.0.1'].includes(location.hostname);
const dateText = t => t?.toDate ? new Intl.DateTimeFormat('id-ID', {timeZone:'Asia/Makassar', day:'2-digit', month:'short', hour:'2-digit', minute:'2-digit'}).format(t.toDate()) + ' WITA' : 'Baru saja';
const demoJob = { id:'demo', symbol:'COINBASE:BTCUSD', timeframe:'H1', mode:'auto', drawings:['support_resistance'], status:'completed', createdAt:{toDate:()=>new Date()}, result:{text:'CONTOH TAMPILAN — bukan analisis pasar aktual.\n\nStruktur pasar\nHasil analisis dari bridge akan muncul di sini, mencakup struktur harga, area penting, dan skenario bersyarat.\n\nArea penting\nLevel support dan resistance disusun dari data chart TradingView.\n\nDrawing\nRingkasan drawing yang berhasil dibuat serta keterbatasannya akan dicantumkan di bagian ini.', screenshot:null} };
function friendly(error) {
  return ({'auth/popup-closed-by-user':'Login dibatalkan. Silakan coba lagi.', 'auth/popup-blocked':'Browser memblokir jendela login. Izinkan pop-up lalu coba lagi.', 'auth/unauthorized-domain':'Domain ini belum diizinkan di Firebase Authentication. Lihat SETUP.md.', 'auth/operation-not-allowed':'Login Google belum diaktifkan di Firebase Authentication.', 'auth/network-request-failed':'Koneksi gagal. Periksa internet Anda.', 'permission-denied':'Akses Firestore ditolak. Periksa akun dan Firestore Rules.', 'failed-precondition':'Riwayat membutuhkan indeks Firestore. Ikuti petunjuk indeks di SETUP.md.', 'unavailable':'Firebase belum dapat dijangkau. Periksa koneksi internet.'})[error.code] || error.message || 'Terjadi kesalahan. Silakan coba kembali.';
}
function ChartArt() {
  return <svg className="chart-art" viewBox="0 0 520 170" fill="none" aria-hidden="true"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#b9ed7d" stopOpacity=".15"/><stop offset="1" stopColor="#b9ed7d" stopOpacity="0"/></linearGradient></defs>{[30,70,110,150].map(y=><path key={y} d={`M0 ${y}H520`} stroke="#293129" strokeDasharray="3 6"/>)}<path d="M0 138 30 131 58 142 89 112 119 121 149 91 180 102 210 79 239 97 269 69 299 84 328 44 359 61 390 30 420 42 451 12 480 26 520 8V170H0Z" fill="url(#fade)"/>{Array.from({length:21},(_,i)=>{const y=133-i*5+(i%3)*9;const down=i%3===1;return <g key={i} stroke={down?'#768d72':'#bce986'}><path d={`M${16+i*24} ${y-18}v42`}/><rect x={11+i*24} y={y-8} width="10" height={down?13:22} rx="1" fill={down?'#39463b':'#bce986'}/></g>})}</svg>;
}
export default function App() {
  const [user,setUser]=useState(DEMO?{uid:'demo',displayName:'Pengguna Demo'}:null), [authLoading,setAuthLoading]=useState(!DEMO), [authBusy,setAuthBusy]=useState(false);
  const [symbol,setSymbol]=useState(PRESETS[0]), [custom,setCustom]=useState(''), [timeframe,setTimeframe]=useState('H1'), [mode,setMode]=useState('auto'), [drawings,setDrawings]=useState(['support_resistance','trendline']), [instruction,setInstruction]=useState('');
  const [jobs,setJobs]=useState(DEMO?[demoJob]:[]), [selected,setSelected]=useState(null), [loading,setLoading]=useState(false), [sending,setSending]=useState(false), [error,setError]=useState(''), [toast,setToast]=useState(''), [online,setOnline]=useState(navigator.onLine), [pageSize,setPageSize]=useState(30), [retry,setRetry]=useState(0);
  const [installPrompt,setInstallPrompt]=useState(null), [installHelp,setInstallHelp]=useState(false), [installed,setInstalled]=useState(matchMedia('(display-mode: standalone)').matches);
  const submitLock=useRef(false), toastTimer=useRef(), demoTimers=useRef([]), activeUid=useRef(user?.uid);
  const {needRefresh:[needRefresh], updateServiceWorker} = useRegisterSW({onRegisterError:()=>setToast('Cache offline belum siap. Muat ulang saat internet tersedia.')});
  function notify(message) {setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6000);}
  useEffect(()=>{if(DEMO)return;return onAuthStateChanged(auth,u=>{activeUid.current=u?.uid;setUser(u);setJobs([]);setSelected(null);setError('');setAuthLoading(false);},e=>{setError(friendly(e));setAuthLoading(false);});},[]);
  useEffect(()=>{if(!user || DEMO)return;setLoading(true);setError('');const q=query(collection(db,'analysisRequests'),where('userId','==',user.uid),orderBy('createdAt','desc'),limit(pageSize));return onSnapshot(q,s=>{setJobs(s.docs.map(d=>({id:d.id,...d.data()})));setLoading(false);setError('');},e=>{setError(friendly(e));setLoading(false);});},[user,pageSize,retry]);
  useEffect(()=>{const timers=demoTimers.current;const on=()=>setOnline(true),off=()=>setOnline(false),before=e=>{e.preventDefault();setInstallPrompt(e);},done=()=>{setInstalled(true);setInstallPrompt(null);};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',done);clearTimeout(toastTimer.current);timers.forEach(clearTimeout);};},[]);
  async function login(){if(DEMO)return;setAuthBusy(true);try{await signInWithPopup(auth,provider);notify('Berhasil masuk. Ruang analisis siap digunakan.');}catch(e){notify(friendly(e));}finally{setAuthBusy(false);}}
  async function logout(){try{await signOut(auth);setJobs([]);setSelected(null);notify('Anda telah keluar.');}catch(e){notify(friendly(e));}}
  async function install(){if(!installPrompt){setInstallHelp(true);return;}await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);}
  async function submit(e){e.preventDefault();if(submitLock.current)return;if(!user){await login();return;}if(!online){notify('Anda sedang offline. Sambungkan internet sebelum mengirim.');return;}let data;try{data=validateRequest({symbol:symbol==='custom'?custom.trim().toUpperCase():symbol,timeframe,mode,drawings,instruction});}catch(err){notify(err.message);return;}submitLock.current=true;setSending(true);const uid=user.uid;try{if(DEMO){const id=crypto.randomUUID();setJobs(j=>[{...data,id,status:'pending',createdAt:{toDate:()=>new Date()},result:null},...j]);setSelected(id);demoTimers.current.push(setTimeout(()=>setJobs(j=>j.map(x=>x.id===id?{...x,status:'processing'}:x)),1500),setTimeout(()=>setJobs(j=>j.map(x=>x.id===id?{...x,status:'completed',result:demoJob.result}:x)),4500));notify('Simulasi dikirim. Tidak ada data yang disimpan ke Firebase.');}else{const doc=await addDoc(collection(db,'analysisRequests'),{...data,userId:uid,status:'pending',createdAt:serverTimestamp(),startedAt:null,completedAt:null,result:null,error:null});if(activeUid.current===uid){setSelected(doc.id);notify('Permintaan terkirim. Menunggu bridge di laptop.');}}}catch(err){notify(friendly(err));}finally{submitLock.current=false;setSending(false);}}
  const current=jobs.find(j=>j.id===selected)||jobs[0];
  const active=jobs.filter(j=>['pending','processing'].includes(j.status)).length;
  return <div className="app-shell"><aside className="sidebar"><a href="#" className="brand"><span className="brand-icon"><ChartCandlestick size={23}/></span><span>TradingView<span className="brand-sub">REMOTE</span></span></a><div className="workspace-label">WORKSPACE <span>01</span></div><nav><a className="nav-item active" href="#analisis"><Layers3 size={18}/>Ruang analisis<span className="nav-dot"/></a><a className="nav-item" href="#riwayat"><History size={18}/>Riwayat permintaan{active>0&&<span className="count">{active}</span>}</a></nav><div className="sidebar-bottom"><div className="local-card"><div className="local-icon"><Radio size={18}/></div><strong>Terhubung melalui Firebase</strong><p>Analisis dikerjakan oleh bridge lokal di laptop Anda.</p><span className="muted micro">Status bridge belum dipantau</span></div><button className="help-button" onClick={()=>setInstallHelp(true)}><CircleHelp size={17}/>Panduan instalasi<ArrowRight size={15}/></button><span className="version">TAHAP 01 <span>v0.1.0</span></span></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>Ruang analisis</strong></div><div className="header-actions"><span className={`connection ${online?'':'offline'}`}><i/>{online?'Online':'Offline'}</span><span className="divider"/>{authLoading?<LoaderCircle className="spin" size={18}/>:user?<><span className="avatar">{user.displayName?.[0]||'U'}</span><span className="user-name">{user.displayName?.split(' ')[0]}</span>{!DEMO&&<button className="icon-button" aria-label="Keluar" onClick={logout}><LogOut size={16}/></button>}</>:<button className="login-small" onClick={login} disabled={authBusy}>Masuk Google <ArrowRight size={14}/></button>}</div></header>
  <main><div className="page-heading"><div><div className="eyebrow"><span/>CHART INTELLIGENCE, ANYWHERE</div><h1>Ruang analisis<span>.</span></h1><p>Kendalikan analisis chart Anda, langsung dari genggaman.</p></div><button className="secondary install" onClick={install} disabled={installed}><ArrowDownToLine size={16}/>{installed?'Aplikasi terinstal':'Instal aplikasi'}</button></div>
  {DEMO&&<div className="notice">Mode demo lokal · Semua hasil dan status di halaman ini adalah simulasi.</div>}{!online&&<div className="error-banner" role="alert">Anda sedang offline. Tampilan aplikasi tersedia; login, pengiriman, dan status realtime memerlukan internet.</div>}
  <section className="hero"><div className="hero-copy"><span className="mini-tag"><Sparkles size={13}/> ASISTEN ANALISIS PERSONAL</span><h2>Chart di laptop.<br/>Kendali di tangan Anda.</h2><p>Pilih aset, tentukan pendekatan, dan biarkan<br className="desktop-break"/> Codex membaca struktur pasar untuk Anda.</p><div className="hero-foot"><ShieldCheck size={14}/> Analisis & drawing saja <span>•</span> Tanpa eksekusi trading</div></div><div className="hero-visual"><div className="chart-label">ANALYSIS WORKSPACE <span>↗</span></div><ChartArt/><span className="art-caption">ILUSTRASI CHART · BUKAN DATA PASAR</span></div></section>
  <div className="workspace-grid"><section className="panel request-panel" id="analisis"><div className="panel-heading"><div className="heading-icon"><Command size={18}/></div><div><h2>Analisis baru</h2><p>Sesuaikan parameter chart Anda.</p></div><span className="step-label">01 — KONFIGURASI</span></div><form onSubmit={submit}>
  <fieldset><legend><span className="step">01</span>Pair / simbol</legend><div className="pair-grid">{PRESETS.map((p,i)=><button type="button" key={p} className={`pair ${symbol===p?'selected':''}`} onClick={()=>setSymbol(p)}><span className={`coin coin-${i}`}>{['₿','Au','€'][i]}</span><span><strong>{['BTC / USD','XAU / USD','EUR / USD'][i]}</strong><small>{['Coinbase','OANDA','Forex'][i]}</small></span>{symbol===p&&<Check size={13}/>}</button>)}</div><button type="button" className={`custom-toggle ${symbol==='custom'?'lime':''}`} onClick={()=>setSymbol(symbol==='custom'?PRESETS[0]:'custom')}>+ Gunakan simbol kustom <ChevronDown size={14}/></button>{symbol==='custom'&&<input aria-label="Simbol kustom" placeholder="Contoh: NASDAQ:AAPL" value={custom} onChange={e=>setCustom(e.target.value.toUpperCase())} maxLength={41} required autoComplete="off"/>}</fieldset>
  <fieldset><legend><span className="step">02</span>Timeframe</legend><div className="timeframes">{TIMEFRAMES.map(t=><button type="button" key={t} aria-pressed={timeframe===t} className={timeframe===t?'selected':''} onClick={()=>setTimeframe(t)}>{t}</button>)}</div></fieldset>
  <fieldset><legend><span className="step">03</span>Drawing <span className="optional">Pilih sesuai kebutuhan</span></legend><div className="drawing-grid">{Object.entries(DRAWINGS).map(([k,v])=><label key={k} className={`drawing ${drawings.includes(k)?'checked':''}`}><input type="checkbox" checked={drawings.includes(k)} onChange={()=>setDrawings(ds=>ds.includes(k)?ds.filter(d=>d!==k):[...ds,k])}/><span>{v}</span></label>)}</div><p className="field-hint">Entry / SL / TP berupa anotasi visual pada chart.</p></fieldset>
  <fieldset><legend><span className="step">04</span>Mode analisis</legend><div className="mode-grid">{Object.entries(MODES).map(([k,v])=><button type="button" aria-pressed={mode===k} key={k} onClick={()=>setMode(k)} className={mode===k?'selected':''}>{k==='auto'&&<Sparkles size={13}/>} {v}</button>)}</div><p className="field-hint">{mode==='auto'?'Codex memilih pendekatan analisis berdasarkan struktur chart.':mode==='instruction'?'Analisis berfokus pada instruksi tambahan yang Anda tulis.':'Gabungkan pembacaan chart otomatis dengan fokus pilihan Anda.'}</p></fieldset>
  <div className="instructions"><label htmlFor="instruction">Instruksi tambahan <span className="optional">{mode==='instruction'?'Wajib':'Opsional'}</span></label><textarea id="instruction" value={instruction} maxLength={MAX_INSTRUCTION} onChange={e=>setInstruction(e.target.value)} placeholder="Contoh: Fokus pada support dan resistance terdekat. Tandai area potensi pembalikan di timeframe H1." rows={3} required={mode==='instruction'}/><span className="char-count">{instruction.length} / 1.500</span></div>
  <button className="primary submit" disabled={sending||authLoading||authBusy||!online}>{sending||authBusy?<LoaderCircle size={18} className="spin"/>:<Sparkles size={18}/>} {sending?'Mengirim permintaan…':!user?'Masuk untuk menganalisis':'Analisis Sekarang'}<ArrowRight size={18}/></button><p className="submit-hint"><ShieldCheck size={12}/> Permintaan diproses aman melalui bridge lokal Anda.</p>
  </form></section>
  <div className="right-column"><section className="panel result-panel"><div className="result-heading"><div><span className="eyebrow">OUTPUT</span><h2>Hasil analisis</h2></div><FileText size={19}/></div>{current?<><div className="result-meta"><strong>{current.symbol}</strong><span>{current.timeframe}</span><span className={`badge ${current.status}`}>{STATUS[current.status]}</span></div><div className="job-progress" aria-label={`Status: ${current.status}`}>{['pending','processing','completed'].map((s,i)=><span key={s} className={['pending','processing','completed'].indexOf(current.status)>=i?'done':''}><i/>{['Antrean','Analisis','Hasil'][i]}</span>)}</div><div className="result-body" aria-live="polite">{current.status==='completed'?<pre>{typeof current.result==='string'?current.result:current.result?.text||'Tidak ada teks hasil.'}</pre>:current.status==='failed'?<div className="job-error"><X size={24}/><h3>Analisis belum berhasil</h3><p>{typeof current.error==='string'?current.error:current.error?.message||'Bridge tidak dapat menyelesaikan permintaan.'}</p><small>Periksa bridge di laptop, lalu kirim analisis baru.</small></div>:<div className="empty-result"><LoaderCircle className="spin" size={32}/><h3>{current.status==='pending'?'Menunggu bridge lokal':'Chart sedang dianalisis'}</h3><p>{current.status==='pending'?'Permintaan tersimpan. Pastikan laptop menyala dan bridge sedang berjalan.':'Codex sedang membaca chart dan menyiapkan drawing pilihan Anda.'}</p></div>}</div><div className="result-footer"><Clock3 size={12}/>{dateText(current.createdAt)}</div></>:<div className="empty-result"><div className="empty-orbit"><ChartCandlestick size={32}/><span className="spark"><Sparkles size={13}/></span></div><h3>Perspektif baru, segera hadir.</h3><p>Hasil pembacaan chart dan ringkasan<br/>drawing akan tampil di sini.</p><span className="empty-pill">Mulai dengan analisis pertama Anda</span></div>}</section>
  {!user&&!authLoading&&<section className="account-card"><div className="google-g">G</div><div><h3>Ruang analisis milik Anda.</h3><p>Masuk untuk mengirim permintaan dan menyimpan riwayat pribadi.</p></div><button className="secondary" disabled={authBusy} onClick={login}>Masuk dengan Google <ArrowRight size={15}/></button></section>}
  <section className="flow-card"><span className="eyebrow">DARI PONSEL KE CHART</span><div className="flow"><span>01<small>Pilih chart</small></span><ArrowRight size={15}/><span>02<small>Bridge lokal</small></span><ArrowRight size={15}/><span>03<small>Lihat hasil</small></span></div><p><Radio size={13}/> Laptop dan TradingView harus aktif saat analisis.</p></section></div></div>
  <section className="panel history-panel" id="riwayat"><div className="history-heading"><div><h2><History size={18}/>Riwayat permintaan</h2><p>Semua analisis Anda, dalam satu tempat.</p></div><span className="micro muted">ASIA / MAKASSAR · WITA</span></div>{error&&<div className="error-banner" role="alert">{error}<button className="secondary" onClick={()=>setRetry(n=>n+1)}>Coba lagi</button></div>}{loading?<div className="history-empty"><LoaderCircle className="spin" size={20}/>Memuat riwayat…</div>:jobs.length?<><div className="history-list">{jobs.map(j=><button key={j.id} className={`history-row ${current?.id===j.id?'chosen':''}`} onClick={()=>{setSelected(j.id);document.querySelector('.result-panel')?.scrollIntoView({behavior:'smooth',block:'center'});}}><span className="history-asset"><Activity size={17}/><strong>{j.symbol}</strong></span><span className="history-detail">{j.timeframe} <span>·</span> {MODES[j.mode]}</span><time>{dateText(j.createdAt)}</time><span className={`badge ${j.status}`}>{STATUS[j.status]||j.status}</span><Expand size={14}/></button>)}</div>{jobs.length>=pageSize&&<button className="secondary load-more" onClick={()=>setPageSize(n=>n+30)}>Muat lebih banyak</button>}</>:<div className="history-empty"><span className="history-empty-icon"><History size={22}/></span><div><strong>Belum ada permintaan</strong><p>{user?'Analisis pertama Anda akan tersimpan di sini.':'Masuk dengan Google untuk melihat riwayat analisis Anda.'}</p></div></div>}</section>
  <footer><span><span className="footer-dot"/>TradingView Remote <span className="muted">/ Ruang untuk keputusan yang lebih terarah.</span></span><span>Dirancang untuk analisis.</span></footer>
  </main></div>{toast&&<div className="toast" role="status">{toast}<button className="icon-button" aria-label="Tutup notifikasi" onClick={()=>setToast('')}><X size={16}/></button></div>}{needRefresh&&<div className="update-banner">Versi baru tersedia.<button className="secondary" onClick={()=>updateServiceWorker(true)}>Perbarui</button></div>}{installHelp&&<div className="modal-backdrop" onClick={()=>setInstallHelp(false)}><section className="install-modal" role="dialog" aria-modal="true" aria-labelledby="install-title" onClick={e=>e.stopPropagation()}><button className="icon-button close" aria-label="Tutup panduan" autoFocus onClick={()=>setInstallHelp(false)}><X size={20}/></button><ArrowDownToLine size={28} className="lime"/><h2 id="install-title">Analisis, satu ketukan saja.</h2><p>Di Chrome Android, buka menu <strong>⋮ → Tambahkan ke layar utama → Instal</strong>. Tombol instal muncul saat browser menyatakan aplikasi siap.</p><p>Instalasi di ponsel memerlukan alamat HTTPS. Preview localhost ini untuk pengujian laptop. Saat offline, aplikasi dapat dibuka; pengiriman analisis memerlukan internet.</p><button className="primary" onClick={()=>setInstallHelp(false)}>Mengerti <Check size={16}/></button></section></div>}</div>;
}
